Repository ssec/sift, pull requests merged in 2019-09, with the labels that each got.

#232 Transition to Satpy for all data reading
  uwsift/__main__.py
  uwsift/common.py
  uwsift/control/layer_tree.py
  uwsift/model/document.py
  uwsift/ui/change_colormap_dialog.ui
  uwsift/ui/custom_widgets.py
  uwsift/ui/open_file_wizard.ui
  uwsift/ui/open_file_wizard_ui.py
  uwsift/ui/pov_main.ui
  uwsift/view/open_file_wizard.py
  uwsift/view/transform.py
  uwsift/workspace/collector.py
  uwsift/workspace/guidebook.py
  uwsift/workspace/importer.py
  uwsift/workspace/metadatabase.py
  uwsift/workspace/workspace.py
Labels: component: workspace, enhancement

#241 Fix probing RGB layers crashes
  uwsift/model/document.py
Labels: bug

#238 Add colorbar option for saving images
  uwsift/data/colormaps/OAX/Cloud Amount Default.cmap
  uwsift/data/colormaps/OAX/Cloud Top Height.cmap
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/ACTP.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/ADP.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/CSM.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/Dust.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/FSC.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/GOES-SST-35.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/RRQPE.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/RRQPE1.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/Smoke.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/VTRSB.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/color-cape-10.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/color-li-10.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/color-pw10-10.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/GOESR-L2/color-pw8-10.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/IR/CIRA (IR Default).cmap
  uwsift/data/colormaps/OAX/GOES-R/IR/IR WV.cmap
  uwsift/data/colormaps/OAX/GOES-R/IR/IR_Color_Clouds_Summer.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/IR/IR_Color_Clouds_Winter.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/IR/Rainbow_11_bit.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/IR/WV_Dry_Yellow.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/IR/dust_and_moisture_split_window.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/IR/enhanced-rainbow-11.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/IR/enhanced-rainbow_warmer_yellow.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/IR/fire_detection_3.9.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/IR/fogdiff_blue.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/IR/ramsdis_IR_12bit.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/IR/ramsdis_WV_12bit.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/Lifted Index/Lifted Index - New CIMSS Table.cmap
  uwsift/data/colormaps/OAX/GOES-R/Lifted Index/Lifted Index Default.cmap
  uwsift/data/colormaps/OAX/GOES-R/Precip/Blended Total Precip Water.cmap
  uwsift/data/colormaps/OAX/GOES-R/Precip/Percent of Normal TPW.cmap
  uwsift/data/colormaps/OAX/GOES-R/Precip/Precip Water - New CIMSS Table.cmap
  uwsift/data/colormaps/OAX/GOES-R/Precip/Precip Water - Polar.cmap
  uwsift/data/colormaps/OAX/GOES-R/Precip/Precip Water Default.cmap
  uwsift/data/colormaps/OAX/GOES-R/Skin Temp/Skin Temp - New CIMSS Table.cmap
  uwsift/data/colormaps/OAX/GOES-R/Skin Temp/Skin Temp Default.cmap
  uwsift/data/colormaps/OAX/GOES-R/VIS/CA (Low Light Vis).cmap
  uwsift/data/colormaps/OAX/GOES-R/VIS/Linear.cmap
  uwsift/data/colormaps/OAX/GOES-R/VIS/VIS_gray_sq-root-12.cmap.md5
  uwsift/data/colormaps/OAX/GOES-R/VIS/ZA (Vis Default).cmap
  uwsift/data/colormaps/OAX/GOES-R/WV/Gray Scale Water Vapor.cmap
  uwsift/data/colormaps/OAX/GOES-R/WV/NSSL VAS (WV Alternate).cmap
  uwsift/data/colormaps/OAX/GOES-R/WV/SLC WV.cmap
  uwsift/data/colormaps/OAX/Low Cloud Base.cmap
  uwsift/data/colormaps/OAX/Rain Rate.cmap
  uwsift/data/colormaps/OAX/prob_severe.cmap.md5
  uwsift/ui/export_image_dialog.ui
  uwsift/ui/export_image_dialog_ui.py
  uwsift/view/colormap.py
  uwsift/view/export_image.py
  uwsift/view/scene_graph.py
Labels: component: ui, enhancement
