Repository ssec/sift, pull requests merged in 2019-12, with the labels that each got.

#249 Add experimental global configuration object using the donfig package
  .travis.yml
  conda-recipe/uwsift/meta.yaml
  setup.py
  uwsift/__init__.py
  uwsift/view/open_file_wizard.py
  uwsift/workspace/collector.py
  uwsift/workspace/importer.py
Labels: enhancement

#270 Fix open file wizard when resolution is a floating point number
  uwsift/__main__.py
  uwsift/common.py
  uwsift/tests/view/test_open_file_wizard.py
  uwsift/view/open_file_wizard.py
  uwsift/workspace/guidebook.py
  uwsift/workspace/importer.py
Labels: bug

#269 Fix grib reader not being included in available readers by default
  uwsift/__init__.py
Labels: bug

#268 Fix incorrect wavelength being taken from Satpy
  README.md
  uwsift/tests/workspace/test_importer.py
  uwsift/workspace/importer.py
Labels: bug

#272 Fix crash during importing when pyproj 2.4.2 is installed
  uwsift/workspace/importer.py
Labels: bug

#273 Add test_requires to setup.py
  setup.py
Labels: build: conda installation, documentation

#275 Recognize GEO-KOMPSAT-2A satellite and LI and GLM instruments
  uwsift/common.py
  uwsift/model/document.py
Labels: bug
