Repository ssec/sift, pull requests merged in 2023-05, with the labels that each got.

#347 Fix or ignore remaining bandit security issues
  build_conda_pack.py
  build_release.py
  continuous_integration/environment.yaml
  uwsift/util/heap_analyzer.py
  uwsift/view/visuals.py
Labels: refactor

#348 Fix conda-pack builds on Windows
  .github/workflows/deploy.yaml
  build_conda_pack.py
  rtd_requirements.txt
Labels: bug, build: binary installer, build: CI

#356 Add missing QML files to source distribution
  MANIFEST.in
Labels: bug, build: binary installer

#358 Update the bundles to use Python 3.11
  .github/workflows/deploy.yaml
Labels: enhancement, build: binary installer

#359 Remove legacy and unused files
  .github/workflows/ci.yaml
  .stickler.yml
  RELEASING.md
  build_release.py
  conda-recipe/matplotlib/bld.bat
  conda-recipe/matplotlib/build.sh
  conda-recipe/matplotlib/cfg_qt4agg.patch
  conda-recipe/matplotlib/meta.yaml
  conda-recipe/matplotlib/osx-frame.patch
  conda-recipe/matplotlib/setupext.patch
  conda-recipe/quamash/bld.bat
  conda-recipe/quamash/build.sh
  conda-recipe/quamash/meta.yaml
  conda-recipe/satpy/meta.yaml
  conda-recipe/sift/meta.yaml
  conda-recipe/vispy/ctypes_fontconfig.diff
  conda-recipe/vispy/meta.yaml
  geometry_tests.ipynb
  id_rsa_sift_sftp.enc
  install_scripts/win-64/Install SIFT.bat
  install_scripts/win-64/README
  install_scripts/win-64/create_shortcuts.py
  install_scripts/win-64/rsync_sift_ahi.bat
  pyproject.toml
  setup.cfg
Labels: build: conda installation, refactor

#360 Reorganize configuration documentation into sub-directory
  doc/source/configuration/area_definitions.rst
  doc/source/configuration/catalogue-auto_update_mode.rst
  doc/source/configuration/default_colormaps.rst
  doc/source/configuration/display.rst
  doc/source/configuration/external_satpy.rst
  doc/source/configuration/index.rst
  doc/source/configuration/latlon-grid-resolution.rst
  doc/source/configuration/logging.rst
  doc/source/configuration/points_styles.rst
  doc/source/configuration/readers.rst
  doc/source/configuration/standard_names.rst
  doc/source/configuration/storage.rst
  doc/source/configuration/units.rst
  doc/source/configuration/watchdog.rst
  doc/source/index.rst
  rtd_requirements.txt
  setup.py
  uwsift/util/heap_profiler.py
Labels: documentation

#363 Migrate contributing and test writing docs from wiki to sphinx
  .readthedocs.yaml
  CONTRIBUTING.rst
  continuous_integration/rtd_environment.yaml
  doc/source/CONTRIBUTING.rst
  doc/source/INSTALLATION-sift.rst
  doc/source/dev_guide/contributing.rst
  doc/source/dev_guide/design_overview.rst
  doc/source/dev_guide/index.rst
  doc/source/dev_guide/writing_tests.rst
  doc/source/index.rst
  doc/source/installation.rst
Labels: documentation

#365 Update Readmes
  CHANGELOG.md
  INSTALLER_README.md
  README.md
Labels: documentation

#364 Implement DYNAMIC kind to handle ambiguous readers like the LI reader
  doc/source/configuration/readers.rst
  uwsift/__init__.py
  uwsift/etc/SIFT/config/readers/li_l1b_bck_nc_sift.yaml
  uwsift/etc/SIFT/config/readers/li_l1b_nc.yaml
  uwsift/etc/SIFT/config/readers/li_l2_a_nc_sift.yaml
  uwsift/etc/SIFT/config/readers/li_l2_nc.yaml
  uwsift/workspace/importer.py
Labels: enhancement, component: workspace

#366 Add support for folder inputs
  uwsift/view/open_file_wizard.py
Labels: enhancement, component: workspace

#367 Update readme for install and contributing docs
  README.md
Labels: documentation
